<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create sample devices
        $devices = [
            [
                'name' => 'Core Switch 1',
                'ip_address' => '192.168.1.1',
                'type' => 'switch',
                'category' => 'Core Network',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'Cisco',
                'model' => 'Catalyst 9300',
                'priority' => 1,
                'uptime_percentage' => 99.9,
                'response_time' => 5,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Core Switch 2',
                'ip_address' => '192.168.1.2',
                'type' => 'switch',
                'category' => 'Core Network',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'Cisco',
                'model' => 'Catalyst 9300',
                'priority' => 1,
                'uptime_percentage' => 99.8,
                'response_time' => 6,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Edge Router 1',
                'ip_address' => '192.168.1.254',
                'type' => 'router',
                'category' => 'Core Network',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'Cisco',
                'model' => 'ISR 4451',
                'priority' => 1,
                'uptime_percentage' => 99.95,
                'response_time' => 8,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Firewall Main',
                'ip_address' => '192.168.1.253',
                'type' => 'firewall',
                'category' => 'Security',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'Fortinet',
                'model' => 'FortiGate 200F',
                'priority' => 1,
                'uptime_percentage' => 99.99,
                'response_time' => 4,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Access Switch Floor 2',
                'ip_address' => '192.168.2.1',
                'type' => 'switch',
                'category' => 'Access Layer',
                'status' => 'up',
                'location' => 'Floor 2 IDF',
                'building' => 'Building A',
                'manufacturer' => 'HP',
                'model' => 'Aruba 2930F',
                'priority' => 3,
                'uptime_percentage' => 98.5,
                'response_time' => 12,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Access Switch Floor 3',
                'ip_address' => '192.168.3.1',
                'type' => 'switch',
                'category' => 'Access Layer',
                'status' => 'warning',
                'location' => 'Floor 3 IDF',
                'building' => 'Building A',
                'manufacturer' => 'HP',
                'model' => 'Aruba 2930F',
                'priority' => 3,
                'uptime_percentage' => 95.2,
                'response_time' => 45,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'WiFi Controller',
                'ip_address' => '192.168.1.10',
                'type' => 'controller',
                'category' => 'Infrastructure',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'Cisco',
                'model' => 'WLC 5520',
                'priority' => 2,
                'uptime_percentage' => 99.7,
                'response_time' => 7,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'AP Floor 2 East',
                'ip_address' => '192.168.2.10',
                'type' => 'access_point',
                'category' => 'Infrastructure',
                'status' => 'up',
                'location' => 'Floor 2 East Wing',
                'building' => 'Building A',
                'manufacturer' => 'Cisco',
                'model' => 'Aironet 3800',
                'priority' => 4,
                'uptime_percentage' => 97.8,
                'response_time' => 15,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'AP Floor 2 West',
                'ip_address' => '192.168.2.11',
                'type' => 'access_point',
                'category' => 'Infrastructure',
                'status' => 'up',
                'location' => 'Floor 2 West Wing',
                'building' => 'Building A',
                'manufacturer' => 'Cisco',
                'model' => 'Aironet 3800',
                'priority' => 4,
                'uptime_percentage' => 98.1,
                'response_time' => 14,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Web Server 1',
                'ip_address' => '192.168.10.10',
                'type' => 'server',
                'category' => 'Servers',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'Dell',
                'model' => 'PowerEdge R740',
                'priority' => 2,
                'uptime_percentage' => 99.95,
                'response_time' => 3,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Database Server',
                'ip_address' => '192.168.10.11',
                'type' => 'server',
                'category' => 'Servers',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'HP',
                'model' => 'ProLiant DL380',
                'priority' => 1,
                'uptime_percentage' => 99.99,
                'response_time' => 2,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
            [
                'name' => 'Backup Server',
                'ip_address' => '192.168.10.12',
                'type' => 'server',
                'category' => 'Servers',
                'status' => 'up',
                'location' => 'Server Room',
                'building' => 'Building A',
                'manufacturer' => 'Dell',
                'model' => 'PowerEdge R640',
                'priority' => 2,
                'uptime_percentage' => 99.9,
                'response_time' => 4,
                'is_monitored' => true,
                'is_active' => true,
                'last_check' => now(),
            ],
        ];

        foreach ($devices as $device) {
            \App\Models\Device::create($device);
        }

        // Create sample alerts
        $alerts = [
            [
                'device_id' => 6, // Access Switch Floor 3
                'type' => 'high_response_time',
                'severity' => 'warning',
                'title' => 'High Response Time Detected',
                'message' => 'Device response time exceeded 40ms threshold',
                'status' => 'open',
                'acknowledged' => false,
            ],
            [
                'device_id' => 6,
                'type' => 'low_uptime',
                'severity' => 'warning',
                'title' => 'Low Uptime Percentage',
                'message' => 'Device uptime dropped below 96%',
                'status' => 'open',
                'acknowledged' => false,
            ],
        ];

        foreach ($alerts as $alert) {
            \App\Models\Alert::create($alert);
        }

        $this->command->info('Sample data seeded successfully!');
    }
}
